In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from config import *
import json
from data_cleaner import *

pd.set_option("display.max_columns", None)  # show all cols
pd.set_option("display.width", None)        # + better readability

In [2]:
csv_path = RUNS_DATA_DIR / 'responses'
files = sorted(csv_path.glob('20260917-*'))

dfs = []
for f in files:
    df_llm = pd.read_csv(f, usecols=['model', 'answer'])
    df_llm['answer'] = df_llm['answer'].apply(json.loads)
    df_answer = pd.json_normalize(df_llm['answer'])
    df_llm = df_llm.drop(columns=['answer']).join(df_answer)
    df_llm['model'] = df_llm['model'].str.split('/').str[1]
    dfs.append(df_llm)

df_llm = pd.concat(dfs, ignore_index=True)
df_llm.head()

,model,id,name,hasFoundMenu,menuLink,format,source
0,claude-sonnet-5,ChIJAV1_vX1SUkYRifHQGs0-33o,Pizze Di Napo Hellerup,True,https://pizzedinapohellerup.dk/,HTML,OFFICIAL_WEBSITE
1,claude-sonnet-5,ChIJ7RIaXXpQUkYRxGD3xBRRltk,McDonald's,True,https://www.mcdonalds.com/dk/da-dk/vores-menu....,HTML,OFFICIAL_WEBSITE
2,claude-sonnet-5,ChIJq6p-9w9TUkYRGJ7PByHSDYY,Byens Pizza,True,http://byens-pizza.dk/?page_id=2065,HTML,OFFICIAL_WEBSITE
3,claude-sonnet-5,ChIJz3lHpeRSUkYRRNH0_-MSMhU,Restaurant Taormina v/Mukuntharaj Karunaratnam,True,https://taormina.dk/menu/,HTML,OFFICIAL_WEBSITE
4,claude-sonnet-5,ChIJBVGBtQFTUkYR7R1FSqjW1kg,Barnetsfest,False,,,

In [3]:
model_menulinks = df_llm.pivot_table(index='id', columns='model', values='menuLink', aggfunc='first')
model_menulinks

model,claude-sonnet-5,gemini-3.7-flash,gpt-5.6-luna,gpt-5.6-terra
id,,,,
ChIJ-7iMbc1TUkYR066Hz1SQ-EI,https://www.restaurantalf.dk/,https://restaurantalf.dk/,https://www.restaurantalf.dk/,https://www.restaurantalf.dk/
ChIJ-QrW55VTUkYRiO5rYIpA5PE,https://durumbar-frb.dk/,https://durumbar78.dk/,https://durumbar2000.dk/,https://www.ubereats.com/dk-en/store/durum-bar...
ChIJ-XF3Wu1TUkYRl25fQ2IL8Ps,https://royalbagel.dk/royal-bagel-valby-langga...,https://wolt.com/da/dnk/copenhagen/restaurant/...,https://wolt.com/da/dnk/copenhagen/restaurant/...,https://www.ubereats.com/dk-en/store/royal-bag...
ChIJ-YewRThSUkYRU-ZX1KiCAr0,https://nordvestpizzaria.dk/,https://www.eatonline.dk/restaurant/172/nord-v...,https://www.eatonline.dk/restaurant/172/nord-v...,https://www.eatonline.dk/restaurant/172/nord-v...
ChIJ-ao52_ZNUkYRU11OTne3ec8,https://www.joejuice.com/,https://www.joejuice.com/menu,https://www.joejuice.com/?market=dk,https://www.ubereats.com/dk-en/store/joe-%26-t...
...,...,...,...,...
ChIJzSGiCwVTUkYRM2XmxLIIRqc,https://www.hallernes.dk/en/standard-smorrebrod/,https://hallernes.dk/,https://www.hallernes.dk/faste-smorrebrod/,https://torvehallerne.hallernes.dk/take-away
ChIJzVHSkstTUkYRp1DtTvwjdlI,,,,
ChIJzX87fApZUkYR3MgmhXk4aXI,,https://www.eatonline.dk/restaurant/190/big-m-...,https://www.eatonline.dk/restaurant/190/big-m-...,https://www.eatonline.dk/restaurant/190/big-m-...
ChIJzZ5rThRUUkYRhi_-x_tvUu0,https://hvidovre.densortegryde.dk/menu.php,https://hvidovre.densortegryde.dk/,https://hvidovre.densortegryde.dk/menu,https://hvidovre.densortegryde.dk/menu
ChIJzy0S399RUkYRIbW-FqClKG8,https://www.just-eat.dk/restaurants-gastronomia13,https://www.gastronomiaitaliana.dk/soeborg/,https://menukort.menu/restaurants/soeborg/gast...,https://menukort.menu/restaurants/soeborg/gast...

In [4]:
discarded_restaurants = [
    "bakery",
    "banquet_hall",
    "bar",
    "bar_and_grill",
    "cafe",
    "car_wash",
    "catering_service",
    "cocktail_bar",
    "coffee_shop",
    "dessert_shop",
    "food_court",
    "gas_station",
    "hot_dog_restaurant",
    "hot_dog_stand",
    "hotel",
    "irish_pub",
    "juice_shop",
    "kebab_shop",
    "meal_takeaway",
    "movie_theater",
    "museum",
    "pastry_shop",
    "point_of_interest",
    "pub",
    "salad_shop",
    "sandwich_shop",
    "shawarma_restaurant",
    "wine_bar",
]

restaurants_to_keep = [
    "argentinian_restaurant",
    "asian_fusion_restaurant",
    "asian_restaurant",
    "bagel_shop",
    "bistro",
    "brazilian_restaurant",
    "brunch_restaurant",
    "buffet_restaurant",
    "chicken_restaurant",
    "chinese_restaurant",
    "danish_restaurant",
    "diner",
    "ethiopian_restaurant",
    "family_restaurant",
    "fast_food_restaurant",
    "fine_dining_restaurant",
    "french_restaurant",
    "fusion_restaurant",
    "greek_restaurant",
    "halal_restaurant",
    "hamburger_restaurant",
    "hawaiian_restaurant",
    "indian_restaurant",
    "indonesian_restaurant",
    "italian_restaurant",
    "japanese_restaurant",
    "korean_restaurant",
    "mexican_restaurant",
    "pakistani_restaurant",
    "persian_restaurant",
    "pizza_delivery",
    "pizza_restaurant",
    "restaurant",
    "seafood_restaurant",
    "spanish_restaurant",
    "sushi_restaurant",
    "thai_restaurant",
    "turkish_restaurant",
    "vegetarian_restaurant",
    "vietnamese_restaurant",
]

In [5]:
df = get_df()
df

,id,name,formattedAddress,primaryType,googleMapsUri,websiteUri,businessStatus,rating,takeout,delivery,dineIn,servesBreakfast,servesLunch,servesDinner,servesBrunch,servesDessert,servesVegetarianFood,priceLevel,startPrice,endPrice,lat,lon,claude-sonnet-5,gemini-3.7-flash,gpt-5.6-luna,gpt-5.6-terra
0,ChIJAV1_vX1SUkYRifHQGs0-33o,Pizze Di Napo Hellerup,"Strandvejen 149, 2900 Hellerup, Denmark",pizza_restaurant,https://maps.google.com/?cid=88538644430728032...,https://platia.dk/pizze-di-napo-hellerup,OPERATIONAL,4.5,1.0,NaN,1.0,0.0,1.0,1.0,0.0,1.0,NaN,PRICE_LEVEL_MODERATE,1,100,55.730339,12.576235,https://pizzedinapohellerup.dk/,https://platia.dk/pizze-di-napo-hellerup,https://platia.dk/pizze-di-napo-hellerup,https://platia.dk/pizze-di-napo-hellerup
1,ChIJ7RIaXXpQUkYRxGD3xBRRltk,McDonald's,"Tempovej 1, 2750 Ballerup, Denmark",fast_food_restaurant,https://maps.google.com/?cid=15678808302382702...,https://www.mcdonalds.com/dk/da-dk/location/ba...,OPERATIONAL,3.5,1.0,1.0,1.0,1.0,1.0,1.0,NaN,1.0,1.0,PRICE_LEVEL_MODERATE,100,200,55.722229,12.384433,https://www.mcdonalds.com/dk/da-dk/vores-menu....,https://www.mcdonalds.com/dk/da-dk/menu.html,https://www.mcdonalds.com/dk/da-dk/vores-menu....,https://www.mcdonalds.com/dk/da-dk/vores-menu....
2,ChIJq6p-9w9TUkYRGJ7PByHSDYY,Byens Pizza,"Nørregade 45c, 1165 København, Denmark",restaurant,https://maps.google.com/?cid=96596078150863826...,http://byens-pizza.dk/?page_id=2065,OPERATIONAL,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,55.681833,12.570881,http://byens-pizza.dk/?page_id=2065,http://byens-pizza.dk/?page_id=2065,,
3,ChIJz3lHpeRSUkYRRNH0_-MSMhU,Restaurant Taormina v/Mukuntharaj Karunaratnam,"Slagelsegade 24, 2100 København, Denmark",restaurant,https://maps.google.com/?cid=15273039940931300...,https://taormina.dk/,OPERATIONAL,4.3,NaN,0.0,1.0,0.0,NaN,1.0,0.0,1.0,NaN,PRICE_LEVEL_MODERATE,200,300,55.698545,12.581154,https://taormina.dk/menu/,https://taormina.dk/menukort/,https://taormina.dk/wp-content/uploads/2025/02...,https://taormina.dk/wp-content/uploads/2025/02...
4,ChIJBVGBtQFTUkYR7R1FSqjW1kg,Barnetsfest,"Blegdamsvej 24, 2200 København, Denmark",family_restaurant,https://maps.google.com/?cid=52486184340357851...,http://www.barnetsfest.dk/,OPERATIONAL,NaN,NaN,0.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,NaN,55.692536,12.564688,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,ChIJIVvKl3tSUkYR8c102BthH2o,Quickstop Kebab,"Ryvangs Allé 82, 2900 Hellerup, Denmark",fast_food_restaurant,https://maps.google.com/?cid=76469374645219363...,NaN,OPERATIONAL,3.7,1.0,NaN,1.0,NaN,1.0,1.0,NaN,0.0,NaN,NaN,1,100,55.731145,12.568325,,https://www.ubereats.com/dk/store/quickstop-ke...,https://www.ubereats.com/dk/store/quickstop-ke...,https://www.ubereats.com/dk/store/quickstop-ke...
300,ChIJ8b1giXNTUkYRMZf6GkCwydQ,Aa,"Griffenfeldsgade 22, 2200 København, Denmark",restaurant,https://maps.google.com/?cid=15332980195736590...,NaN,OPERATIONAL,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.688363,12.554492,,,,https://www.elgoldie.dk/menu
301,ChIJB0qmbeutU0YReOf8DohKutg,Sushi Joint,"Amager Strandvej 140 B, 2300 København, Denmark",sushi_restaurant,https://maps.google.com/?cid=15616876606088079...,https://sushi-joint.dk/,OPERATIONAL,4.5,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,PRICE_LEVEL_MODERATE,200,300,55.658541,12.634693,https://sushi-joint.dk/product-category/sushi-...,https://sushi-joint.dk/,https://sushi-joint.dk/,https://sushi-joint.dk/product-category/sushi-...
302,ChIJOYBjSkZRUkYRWyyVofnZAJE,Hanedan Restaurant,"Valhøjs Alle 67A, 2610 Rødovre, Denmark",turkish_restaurant,https://maps.google.com/?cid=10448590801680542...,http://hanedan.dk/,OPERATIONAL,3.9,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,PRICE_LEVEL_MODERATE,100,200,55.672897,12.453116,https://hanedan.dk/menu/,http://hanedan.dk/menukort/,https://hanedan.dk/wp-content/uploads/2025/03/...,https://hanedan.dk/wp-content/uploads/2026/08/...
303,ChIJfdx9lAD4UkYRnvtpMhvsZh4,SuSandwich,"Greve Strandvej 4A, 2670 Greve, Denmark",restaurant,https://maps.google.com/?cid=21906978703164036...,NaN,OPERATIONAL,4.4,1.0,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,100,200,55.583299,12.313063,,,,